name: GitHub Pages

on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Install pnpm
      run: npm install -g pnpm
    - name: Install dependencies
      run: pnpm install
    - name: Build packages/protester
      working-directory: ./packages/protester
      run: pnpm run build
    - name: Build packages/decharge
      working-directory: ./packages/decharge
      run: pnpm run build
    - name: Build examples/project-website
      working-directory: ./examples/project-website
      run: BASE=decharge/ pnpm run build
    - name: Deploy website
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./examples/project-website/dist
    - name: Semantic versioning
      working-directory: ./packages/decharge
      run: pnpm run semantic-release